version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
      - rabbitmq
    env_file:
      - .env
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  smtp:
    image: instrumentisto/postfix
    container_name: smtp-server
    environment:
      - MAIL_DOMAIN=example.com  
      - SMTP_USER=username:password  
    ports:
      - "25:25"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
